### ISSUE TITLE
Respect original whitespace, specifically non-breaking space

### ISSUE THREAD

**Issue by jayliu50** [zeke/ap-style-title-case#10]
`titleCase("About preventing\u00a0widows")`:

results in `"About Preventing Widows"`
expected `"About Preventing\u00a0Widows"`

**Comment by wooorm** [comment]
Sure, PR welcome!

**Comment by wooorm** [comment]
Want to work on a PR?

**Comment by wooorm** [comment]
This has always been supported with `options.keepSpaces: true`.
