### ISSUE TITLE
AP versus APA: differences in capitalizing the last word of a title

### ISSUE THREAD

**Issue by evanbaldonado** [zeke/ap-style-title-case#8]
Hi, I noticed that this project indicates that AP style and APA style have identical rules for title capitalization and thus treats the two interchangeably.

However, from [this page](https://titlecaseconverter.com/), I found out that "AP, CMOS, MLA, the New York Times, and Wikipedia have a rule to always capitalize the last word of a title. AMA, APA, and Bluebook do not have such a rule, which means a preposition at the end of a title is lowercased in these styles (_Be Careful What You Wish for_)."

Could you add an option for us to include a preference on whether to capitalize the last words of titles, please? Thank you for all of your work on this project.

**Comment by wooorm** [comment]
Hiya! I’m not too familiar with this. But if what you‘re saying is correct, then a PR would be welcome!

**Comment by wooorm** [comment]
PR welcome!
