### ISSUE TITLE
Converting `ap-style-title-case` to use ES6 modules

### ISSUE THREAD

**Issue by jkhaui** [zeke/ap-style-title-case#9]
Thank you for your simple but powerful package. It's my go-to JS library when having to work with various unformatted strings.

**Can I request that your library is updated to use modern ES6 modules and namespacing?** This would make it much nicer to integrate with JavaScript-heavy projects, as one could simply use the same syntax alongside other named imports, e.g. `import { titleCase } from ...` as opposed to the more cumbersome `const titleCase = require(".../")` approach.

If you no longer maintain this library - or aren't willing to implement this change - I could submit a PR. Alternatively I could fork the package and publish a new version on NPM. It's a small change but it's beneficial as I use this lib across so many different projects. Let me know if you are OK with my suggestions, and/or which project you would prefer.

Take care :)

**Comment by wooorm** [comment]
Assuming you are using ESM in a capable bundler or Node itself, you could already import it?

```js
import titleCase from 'ap-style-title-case'
```

https://nodejs.org/api/esm.html#esm_import_statements

**Comment by jkhaui** [comment]
You're totally right and I have no idea why I thought you couldn't... Might have had some weird setup or something in the past :\

Thanks!
